import zmq
import flatbuffers
import time
import numpy as np
import tensorflow as tf

# import modules generated by flatc
# verify if the folder with the modules is in the same directory as this file
import NerfDistributed.RayBatch as RayBatch
import NerfDistributed.RenderResult as RenderResult

from nerf_core.model import init_model, render_rays, get_rays_slice

def main():
    print("Starting worker...")

    print("Initing model...")
    model = init_model()

    print("Loading model...")
    model.load_weights('data/weights.h5')

    # config socket ZeroMQ
    context = zmq.Context()
    socket = context.socket(zmq.REQ)
    socket.bind("tcp://localhost:5555") #TODO: pass as a parameter
    
    print("worker connected. requesting work...\n")

    # initial handshake - signal to receive the first batch
    socket.send(b"READY")

    while True:
        # rcever master's connection
        message = socket.recv()
        print(f"[>] receved message! length: {len(message)} bytes")

        # decode using FlatBuffers (Zero-copy parse)
        # start offset is always 0
        ray_batch = RayBatch.RayBatch.GetRootAsRayBatch(message, 0)

        batch_id = ray_batch.BatchId()

        # poison pill
        if batch_id == -1:
            print("[X] termination signal received (batch_id = -1). terminating...")
            break

        # extract basic data
        start_idx = ray_batch.StartIdx()
        end_idx = ray_batch.EndIdx()
        H = ray_batch.H()
        W = ray_batch.W()
        focal = ray_batch.Focal()
        near = ray_batch.Near()
        far = ray_batch.Far()
        n_samples = ray_batch.NSamples()

        pose_flat = ray_batch.PoseMatrixAsNumpy()
        c2w = np.array(pose_flat).reshape(4, 4)

        # c2w needs to be in tensorflow float32 format
        c2w_tf = tf.cast(c2w, dtype=tf.float32)

        print(f"    - Batch ID : {batch_id}")
        print(f"    - Start_idx : {start_idx}")
        print(f"    - End_idx : {end_idx}")
        print(f"    - H : {H}")
        print(f"    - W : {W}")
        print(f"    - Focal : {focal}")
        print(f"    - Near : {near}")
        print(f"    - Far : {far}")
        print(f"    - N_Samples : {n_samples}")

        rays_o, rays_d = get_rays_slice(H, W, focal, c2w_tf, start_idx, end_idx)
        rgb_map, depth_map, acc_map = render_rays(model, rays_o, rays_d, near, far, n_samples)

        num_rays_processed = end_idx - start_idx

        # Flatten the resulting TensorFlow tensors for transmission over the network
        rgb_flat = rgb_map.numpy().flatten()
        depth_flat = depth_map.numpy().flatten()

        # Init memory buffer (auto-resizes if needed)
        builder = flatbuffers.Builder(1024)

        # pack vectors
        # flatuffers builds bottom-up (backwards) to prevent memory reallocation/copies
        RenderResult.RenderResultStartRgbMapVector(builder, len(rgb_flat))
        for x in reversed(rgb_flat):
            builder.PrependFloat32(x)   # prepend in reverse so it reads forward in memory
        rgb_vec = builder.EndVector()   # returns a pointer, not the array

        RenderResult.RenderResultStartDepthMapVector(builder, len(depth_flat))
        for x in reversed(depth_flat):
            builder.PrependFloat32(x)
        depth_vec = builder.EndVector()

        # construct main response table
        # main table must be built AFTER its nested vectors are created
        # the vectors were created above
        RenderResult.RenderResultStart(builder)
        RenderResult.RenderResultAddBatchId(builder, batch_id)
        RenderResult.RenderResultAddNumRays(builder, num_rays_processed)
        
        # store only references to the vectors (enabling zero-copy deserialization)
        RenderResult.RenderResultAddRgbMap(builder, rgb_vec)
        RenderResult.RenderResultAddDepthMap(builder, depth_vec)

        result = RenderResult.RenderResultEnd(builder)
        builder.Finish(result)

        # send
        response_bytes = builder.Output()
        socket.send(response_bytes)

        print(f"[<] Response sent! ({len(response_bytes)} bytes)\n")

    socket.close()
    context.term()

if __name__ == "__main__":
    main()
