# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NerfDistributed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RayBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RayBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRayBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RayBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RayBatch
    def BatchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def NumRays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def RaysO(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RayBatch
    def RaysOAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # RayBatch
    def RaysOLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RayBatch
    def RaysOIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RayBatch
    def RaysD(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RayBatch
    def RaysDAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # RayBatch
    def RaysDLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RayBatch
    def RaysDIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RayBatch
    def Near(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 2.0

    # RayBatch
    def Far(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 6.0

    # RayBatch
    def NSamples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 64

def RayBatchStart(builder):
    builder.StartObject(7)

def Start(builder):
    RayBatchStart(builder)

def RayBatchAddBatchId(builder, batchId):
    builder.PrependInt32Slot(0, batchId, 0)

def AddBatchId(builder, batchId):
    RayBatchAddBatchId(builder, batchId)

def RayBatchAddNumRays(builder, numRays):
    builder.PrependInt32Slot(1, numRays, 0)

def AddNumRays(builder, numRays):
    RayBatchAddNumRays(builder, numRays)

def RayBatchAddRaysO(builder, raysO):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(raysO), 0)

def AddRaysO(builder, raysO):
    RayBatchAddRaysO(builder, raysO)

def RayBatchStartRaysOVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRaysOVector(builder, numElems):
    return RayBatchStartRaysOVector(builder, numElems)

def RayBatchAddRaysD(builder, raysD):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(raysD), 0)

def AddRaysD(builder, raysD):
    RayBatchAddRaysD(builder, raysD)

def RayBatchStartRaysDVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRaysDVector(builder, numElems):
    return RayBatchStartRaysDVector(builder, numElems)

def RayBatchAddNear(builder, near):
    builder.PrependFloat32Slot(4, near, 2.0)

def AddNear(builder, near):
    RayBatchAddNear(builder, near)

def RayBatchAddFar(builder, far):
    builder.PrependFloat32Slot(5, far, 6.0)

def AddFar(builder, far):
    RayBatchAddFar(builder, far)

def RayBatchAddNSamples(builder, nSamples):
    builder.PrependInt32Slot(6, nSamples, 64)

def AddNSamples(builder, nSamples):
    RayBatchAddNSamples(builder, nSamples)

def RayBatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return RayBatchEnd(builder)
