# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NerfDistributed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RayBatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RayBatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRayBatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RayBatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RayBatch
    def BatchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def StartIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def EndIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def H(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def W(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RayBatch
    def Focal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # RayBatch
    def PoseMatrix(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RayBatch
    def PoseMatrixAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # RayBatch
    def PoseMatrixLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RayBatch
    def PoseMatrixIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # RayBatch
    def Near(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 2.0

    # RayBatch
    def Far(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 6.0

    # RayBatch
    def NSamples(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 64

def RayBatchStart(builder):
    builder.StartObject(10)

def Start(builder):
    RayBatchStart(builder)

def RayBatchAddBatchId(builder, batchId):
    builder.PrependInt32Slot(0, batchId, 0)

def AddBatchId(builder, batchId):
    RayBatchAddBatchId(builder, batchId)

def RayBatchAddStartIdx(builder, startIdx):
    builder.PrependInt32Slot(1, startIdx, 0)

def AddStartIdx(builder, startIdx):
    RayBatchAddStartIdx(builder, startIdx)

def RayBatchAddEndIdx(builder, endIdx):
    builder.PrependInt32Slot(2, endIdx, 0)

def AddEndIdx(builder, endIdx):
    RayBatchAddEndIdx(builder, endIdx)

def RayBatchAddH(builder, h):
    builder.PrependInt32Slot(3, h, 0)

def AddH(builder, h):
    RayBatchAddH(builder, h)

def RayBatchAddW(builder, w):
    builder.PrependInt32Slot(4, w, 0)

def AddW(builder, w):
    RayBatchAddW(builder, w)

def RayBatchAddFocal(builder, focal):
    builder.PrependFloat32Slot(5, focal, 0.0)

def AddFocal(builder, focal):
    RayBatchAddFocal(builder, focal)

def RayBatchAddPoseMatrix(builder, poseMatrix):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(poseMatrix), 0)

def AddPoseMatrix(builder, poseMatrix):
    RayBatchAddPoseMatrix(builder, poseMatrix)

def RayBatchStartPoseMatrixVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPoseMatrixVector(builder, numElems):
    return RayBatchStartPoseMatrixVector(builder, numElems)

def RayBatchAddNear(builder, near):
    builder.PrependFloat32Slot(7, near, 2.0)

def AddNear(builder, near):
    RayBatchAddNear(builder, near)

def RayBatchAddFar(builder, far):
    builder.PrependFloat32Slot(8, far, 6.0)

def AddFar(builder, far):
    RayBatchAddFar(builder, far)

def RayBatchAddNSamples(builder, nSamples):
    builder.PrependInt32Slot(9, nSamples, 64)

def AddNSamples(builder, nSamples):
    RayBatchAddNSamples(builder, nSamples)

def RayBatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return RayBatchEnd(builder)
