# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NerfDistributed

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RenderResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RenderResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRenderResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RenderResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RenderResult
    def BatchId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RenderResult
    def NumRays(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # RenderResult
    def RgbMap(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RenderResult
    def RgbMapAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # RenderResult
    def RgbMapLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RenderResult
    def RgbMapIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RenderResult
    def DepthMap(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RenderResult
    def DepthMapAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # RenderResult
    def DepthMapLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RenderResult
    def DepthMapIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def RenderResultStart(builder):
    builder.StartObject(4)

def Start(builder):
    RenderResultStart(builder)

def RenderResultAddBatchId(builder, batchId):
    builder.PrependInt32Slot(0, batchId, 0)

def AddBatchId(builder, batchId):
    RenderResultAddBatchId(builder, batchId)

def RenderResultAddNumRays(builder, numRays):
    builder.PrependInt32Slot(1, numRays, 0)

def AddNumRays(builder, numRays):
    RenderResultAddNumRays(builder, numRays)

def RenderResultAddRgbMap(builder, rgbMap):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(rgbMap), 0)

def AddRgbMap(builder, rgbMap):
    RenderResultAddRgbMap(builder, rgbMap)

def RenderResultStartRgbMapVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRgbMapVector(builder, numElems):
    return RenderResultStartRgbMapVector(builder, numElems)

def RenderResultAddDepthMap(builder, depthMap):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(depthMap), 0)

def AddDepthMap(builder, depthMap):
    RenderResultAddDepthMap(builder, depthMap)

def RenderResultStartDepthMapVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDepthMapVector(builder, numElems):
    return RenderResultStartDepthMapVector(builder, numElems)

def RenderResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return RenderResultEnd(builder)
