// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_
#define FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace NerfDistributed {

struct RayBatch;
struct RayBatchBuilder;

struct RenderResult;
struct RenderResultBuilder;

struct RayBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RayBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BATCH_ID = 4,
    VT_NUM_RAYS = 6,
    VT_RAYS_O = 8,
    VT_RAYS_D = 10,
    VT_NEAR = 12,
    VT_FAR = 14,
    VT_N_SAMPLES = 16
  };
  int32_t batch_id() const {
    return GetField<int32_t>(VT_BATCH_ID, 0);
  }
  int32_t num_rays() const {
    return GetField<int32_t>(VT_NUM_RAYS, 0);
  }
  const ::flatbuffers::Vector<float> *rays_o() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RAYS_O);
  }
  const ::flatbuffers::Vector<float> *rays_d() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RAYS_D);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 2.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 6.0f);
  }
  int32_t n_samples() const {
    return GetField<int32_t>(VT_N_SAMPLES, 64);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_NUM_RAYS, 4) &&
           VerifyOffset(verifier, VT_RAYS_O) &&
           verifier.VerifyVector(rays_o()) &&
           VerifyOffset(verifier, VT_RAYS_D) &&
           verifier.VerifyVector(rays_d()) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           VerifyField<int32_t>(verifier, VT_N_SAMPLES, 4) &&
           verifier.EndTable();
  }
};

struct RayBatchBuilder {
  typedef RayBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_batch_id(int32_t batch_id) {
    fbb_.AddElement<int32_t>(RayBatch::VT_BATCH_ID, batch_id, 0);
  }
  void add_num_rays(int32_t num_rays) {
    fbb_.AddElement<int32_t>(RayBatch::VT_NUM_RAYS, num_rays, 0);
  }
  void add_rays_o(::flatbuffers::Offset<::flatbuffers::Vector<float>> rays_o) {
    fbb_.AddOffset(RayBatch::VT_RAYS_O, rays_o);
  }
  void add_rays_d(::flatbuffers::Offset<::flatbuffers::Vector<float>> rays_d) {
    fbb_.AddOffset(RayBatch::VT_RAYS_D, rays_d);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(RayBatch::VT_NEAR, near, 2.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(RayBatch::VT_FAR, far, 6.0f);
  }
  void add_n_samples(int32_t n_samples) {
    fbb_.AddElement<int32_t>(RayBatch::VT_N_SAMPLES, n_samples, 64);
  }
  explicit RayBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RayBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RayBatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RayBatch> CreateRayBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> rays_o = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> rays_d = 0,
    float near = 2.0f,
    float far = 6.0f,
    int32_t n_samples = 64) {
  RayBatchBuilder builder_(_fbb);
  builder_.add_n_samples(n_samples);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_rays_d(rays_d);
  builder_.add_rays_o(rays_o);
  builder_.add_num_rays(num_rays);
  builder_.add_batch_id(batch_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RayBatch> CreateRayBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    const std::vector<float> *rays_o = nullptr,
    const std::vector<float> *rays_d = nullptr,
    float near = 2.0f,
    float far = 6.0f,
    int32_t n_samples = 64) {
  auto rays_o__ = rays_o ? _fbb.CreateVector<float>(*rays_o) : 0;
  auto rays_d__ = rays_d ? _fbb.CreateVector<float>(*rays_d) : 0;
  return NerfDistributed::CreateRayBatch(
      _fbb,
      batch_id,
      num_rays,
      rays_o__,
      rays_d__,
      near,
      far,
      n_samples);
}

struct RenderResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenderResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BATCH_ID = 4,
    VT_NUM_RAYS = 6,
    VT_RGB_MAP = 8,
    VT_DEPTH_MAP = 10
  };
  int32_t batch_id() const {
    return GetField<int32_t>(VT_BATCH_ID, 0);
  }
  int32_t num_rays() const {
    return GetField<int32_t>(VT_NUM_RAYS, 0);
  }
  const ::flatbuffers::Vector<float> *rgb_map() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RGB_MAP);
  }
  const ::flatbuffers::Vector<float> *depth_map() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DEPTH_MAP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_NUM_RAYS, 4) &&
           VerifyOffset(verifier, VT_RGB_MAP) &&
           verifier.VerifyVector(rgb_map()) &&
           VerifyOffset(verifier, VT_DEPTH_MAP) &&
           verifier.VerifyVector(depth_map()) &&
           verifier.EndTable();
  }
};

struct RenderResultBuilder {
  typedef RenderResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_batch_id(int32_t batch_id) {
    fbb_.AddElement<int32_t>(RenderResult::VT_BATCH_ID, batch_id, 0);
  }
  void add_num_rays(int32_t num_rays) {
    fbb_.AddElement<int32_t>(RenderResult::VT_NUM_RAYS, num_rays, 0);
  }
  void add_rgb_map(::flatbuffers::Offset<::flatbuffers::Vector<float>> rgb_map) {
    fbb_.AddOffset(RenderResult::VT_RGB_MAP, rgb_map);
  }
  void add_depth_map(::flatbuffers::Offset<::flatbuffers::Vector<float>> depth_map) {
    fbb_.AddOffset(RenderResult::VT_DEPTH_MAP, depth_map);
  }
  explicit RenderResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenderResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenderResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RenderResult> CreateRenderResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> rgb_map = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> depth_map = 0) {
  RenderResultBuilder builder_(_fbb);
  builder_.add_depth_map(depth_map);
  builder_.add_rgb_map(rgb_map);
  builder_.add_num_rays(num_rays);
  builder_.add_batch_id(batch_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RenderResult> CreateRenderResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    const std::vector<float> *rgb_map = nullptr,
    const std::vector<float> *depth_map = nullptr) {
  auto rgb_map__ = rgb_map ? _fbb.CreateVector<float>(*rgb_map) : 0;
  auto depth_map__ = depth_map ? _fbb.CreateVector<float>(*depth_map) : 0;
  return NerfDistributed::CreateRenderResult(
      _fbb,
      batch_id,
      num_rays,
      rgb_map__,
      depth_map__);
}

}  // namespace NerfDistributed

#endif  // FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_
