// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_
#define FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace NerfDistributed {

struct RayBatch;
struct RayBatchBuilder;

struct RenderResult;
struct RenderResultBuilder;

struct RayBatch FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RayBatchBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BATCH_ID = 4,
    VT_START_IDX = 6,
    VT_END_IDX = 8,
    VT_H = 10,
    VT_W = 12,
    VT_FOCAL = 14,
    VT_POSE_MATRIX = 16,
    VT_NEAR = 18,
    VT_FAR = 20,
    VT_N_SAMPLES = 22
  };
  int32_t batch_id() const {
    return GetField<int32_t>(VT_BATCH_ID, 0);
  }
  int32_t start_idx() const {
    return GetField<int32_t>(VT_START_IDX, 0);
  }
  int32_t end_idx() const {
    return GetField<int32_t>(VT_END_IDX, 0);
  }
  int32_t h() const {
    return GetField<int32_t>(VT_H, 0);
  }
  int32_t w() const {
    return GetField<int32_t>(VT_W, 0);
  }
  float focal() const {
    return GetField<float>(VT_FOCAL, 0.0f);
  }
  const ::flatbuffers::Vector<float> *pose_matrix() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_POSE_MATRIX);
  }
  float near() const {
    return GetField<float>(VT_NEAR, 2.0f);
  }
  float far() const {
    return GetField<float>(VT_FAR, 6.0f);
  }
  int32_t n_samples() const {
    return GetField<int32_t>(VT_N_SAMPLES, 64);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_START_IDX, 4) &&
           VerifyField<int32_t>(verifier, VT_END_IDX, 4) &&
           VerifyField<int32_t>(verifier, VT_H, 4) &&
           VerifyField<int32_t>(verifier, VT_W, 4) &&
           VerifyField<float>(verifier, VT_FOCAL, 4) &&
           VerifyOffset(verifier, VT_POSE_MATRIX) &&
           verifier.VerifyVector(pose_matrix()) &&
           VerifyField<float>(verifier, VT_NEAR, 4) &&
           VerifyField<float>(verifier, VT_FAR, 4) &&
           VerifyField<int32_t>(verifier, VT_N_SAMPLES, 4) &&
           verifier.EndTable();
  }
};

struct RayBatchBuilder {
  typedef RayBatch Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_batch_id(int32_t batch_id) {
    fbb_.AddElement<int32_t>(RayBatch::VT_BATCH_ID, batch_id, 0);
  }
  void add_start_idx(int32_t start_idx) {
    fbb_.AddElement<int32_t>(RayBatch::VT_START_IDX, start_idx, 0);
  }
  void add_end_idx(int32_t end_idx) {
    fbb_.AddElement<int32_t>(RayBatch::VT_END_IDX, end_idx, 0);
  }
  void add_h(int32_t h) {
    fbb_.AddElement<int32_t>(RayBatch::VT_H, h, 0);
  }
  void add_w(int32_t w) {
    fbb_.AddElement<int32_t>(RayBatch::VT_W, w, 0);
  }
  void add_focal(float focal) {
    fbb_.AddElement<float>(RayBatch::VT_FOCAL, focal, 0.0f);
  }
  void add_pose_matrix(::flatbuffers::Offset<::flatbuffers::Vector<float>> pose_matrix) {
    fbb_.AddOffset(RayBatch::VT_POSE_MATRIX, pose_matrix);
  }
  void add_near(float near) {
    fbb_.AddElement<float>(RayBatch::VT_NEAR, near, 2.0f);
  }
  void add_far(float far) {
    fbb_.AddElement<float>(RayBatch::VT_FAR, far, 6.0f);
  }
  void add_n_samples(int32_t n_samples) {
    fbb_.AddElement<int32_t>(RayBatch::VT_N_SAMPLES, n_samples, 64);
  }
  explicit RayBatchBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RayBatch> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RayBatch>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RayBatch> CreateRayBatch(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t start_idx = 0,
    int32_t end_idx = 0,
    int32_t h = 0,
    int32_t w = 0,
    float focal = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> pose_matrix = 0,
    float near = 2.0f,
    float far = 6.0f,
    int32_t n_samples = 64) {
  RayBatchBuilder builder_(_fbb);
  builder_.add_n_samples(n_samples);
  builder_.add_far(far);
  builder_.add_near(near);
  builder_.add_pose_matrix(pose_matrix);
  builder_.add_focal(focal);
  builder_.add_w(w);
  builder_.add_h(h);
  builder_.add_end_idx(end_idx);
  builder_.add_start_idx(start_idx);
  builder_.add_batch_id(batch_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RayBatch> CreateRayBatchDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t start_idx = 0,
    int32_t end_idx = 0,
    int32_t h = 0,
    int32_t w = 0,
    float focal = 0.0f,
    const std::vector<float> *pose_matrix = nullptr,
    float near = 2.0f,
    float far = 6.0f,
    int32_t n_samples = 64) {
  auto pose_matrix__ = pose_matrix ? _fbb.CreateVector<float>(*pose_matrix) : 0;
  return NerfDistributed::CreateRayBatch(
      _fbb,
      batch_id,
      start_idx,
      end_idx,
      h,
      w,
      focal,
      pose_matrix__,
      near,
      far,
      n_samples);
}

struct RenderResult FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RenderResultBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BATCH_ID = 4,
    VT_NUM_RAYS = 6,
    VT_RGB_MAP = 8,
    VT_DEPTH_MAP = 10
  };
  int32_t batch_id() const {
    return GetField<int32_t>(VT_BATCH_ID, 0);
  }
  int32_t num_rays() const {
    return GetField<int32_t>(VT_NUM_RAYS, 0);
  }
  const ::flatbuffers::Vector<float> *rgb_map() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RGB_MAP);
  }
  const ::flatbuffers::Vector<float> *depth_map() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_DEPTH_MAP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_BATCH_ID, 4) &&
           VerifyField<int32_t>(verifier, VT_NUM_RAYS, 4) &&
           VerifyOffset(verifier, VT_RGB_MAP) &&
           verifier.VerifyVector(rgb_map()) &&
           VerifyOffset(verifier, VT_DEPTH_MAP) &&
           verifier.VerifyVector(depth_map()) &&
           verifier.EndTable();
  }
};

struct RenderResultBuilder {
  typedef RenderResult Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_batch_id(int32_t batch_id) {
    fbb_.AddElement<int32_t>(RenderResult::VT_BATCH_ID, batch_id, 0);
  }
  void add_num_rays(int32_t num_rays) {
    fbb_.AddElement<int32_t>(RenderResult::VT_NUM_RAYS, num_rays, 0);
  }
  void add_rgb_map(::flatbuffers::Offset<::flatbuffers::Vector<float>> rgb_map) {
    fbb_.AddOffset(RenderResult::VT_RGB_MAP, rgb_map);
  }
  void add_depth_map(::flatbuffers::Offset<::flatbuffers::Vector<float>> depth_map) {
    fbb_.AddOffset(RenderResult::VT_DEPTH_MAP, depth_map);
  }
  explicit RenderResultBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RenderResult> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RenderResult>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RenderResult> CreateRenderResult(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> rgb_map = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> depth_map = 0) {
  RenderResultBuilder builder_(_fbb);
  builder_.add_depth_map(depth_map);
  builder_.add_rgb_map(rgb_map);
  builder_.add_num_rays(num_rays);
  builder_.add_batch_id(batch_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RenderResult> CreateRenderResultDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t batch_id = 0,
    int32_t num_rays = 0,
    const std::vector<float> *rgb_map = nullptr,
    const std::vector<float> *depth_map = nullptr) {
  auto rgb_map__ = rgb_map ? _fbb.CreateVector<float>(*rgb_map) : 0;
  auto depth_map__ = depth_map ? _fbb.CreateVector<float>(*depth_map) : 0;
  return NerfDistributed::CreateRenderResult(
      _fbb,
      batch_id,
      num_rays,
      rgb_map__,
      depth_map__);
}

}  // namespace NerfDistributed

#endif  // FLATBUFFERS_GENERATED_NERFMESSAGES_NERFDISTRIBUTED_H_
